name: unique_portfolio
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  audioplayers: ^6.0.0
  firebase_core: ^3.1.0
  flick_video_player: ^0.8.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bounceable: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.13.1
  flutter_pdfview: ^1.3.2
  flutter_widget_from_html: ^0.15.1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  gsheets: ^0.5.0
  http: ^1.2.1
  just_audio: ^0.9.38
  model_viewer_plus: 1.7.2
  responsive_builder: ^0.7.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_launcher: ^6.3.0
  url_strategy: ^0.2.0
  video_player: ^2.8.7
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/appbar_logo.png
    - assets/images/bg.png
    - assets/images/cal.png
    - assets/images/camera.png
    - assets/images/cci.png
    - assets/images/coding_challenge.png
    - assets/images/container.png
    - assets/images/gdsc.png
    - assets/images/gulamu.png
    - assets/images/histel.png
    - assets/images/influencer.png
    - assets/images/informatics.png
    - assets/images/mar.png
    - assets/images/mobile_skils.png
    - assets/images/motion_lab.png
    - assets/images/my_portfolio.png
    - assets/images/profile.png
    - assets/images/rio.png
    - assets/images/roma.png
    - assets/images/romario.png
    - assets/images/skill_set.png
    - assets/images/tv.png
    - assets/images/umaamerika.png
    - assets/images/x_bod.png
    - assets/images/youtube.png
    - assets/icons/dot.png
    - assets/icons/dw_icon.png
    - assets/icons/exit_icon.png
    - assets/icons/fb.png
    - assets/icons/file.png
    - assets/icons/github.png
    - assets/icons/image.png
    - assets/icons/linkedin.png
    - assets/icons/menu_mobile.png
    - assets/icons/porto.png
    - assets/icons/separator.png
    - assets/icons/skill.png
    - assets/icons/wa.png
    - assets/icons/workexperience.png
    - assets/icons/youtube.png
    - assets/images/profile_mobile.png
    - assets/images/histel2.png
    - assets/images/histel1.png
    - assets/images/histel3.png
    - assets/images/histel4.png
    - assets/images/histel5.png
    - assets/images/histel6.png
    - assets/images/gulamu1.png
    - assets/images/gulamu2.png
    - assets/images/gulamu3.png
    - assets/images/gulamu4.png
    - assets/images/gulamu5.png
    - assets/images/terminal1.png
    - assets/images/terminal2.png
    - assets/images/terminal3.png
    - assets/images/terminal4.png
    - assets/images/terminal5.png
    - assets/images/terminal6.png
    - assets/images/coding1.png
    - assets/images/coding2.png
    - assets/images/coding3.png
    - assets/icons/x.png
    - assets/files/cv.pdf
    - assets/music/1.mp3
    - assets/music/2.mp3
    - assets/music/3.mp3
    - assets/music/4.mp3
